name: suprashare
channels:
  - defaults
dependencies:
  - python=3.11
  - setuptools
  - flask
  - flask-sqlalchemy
  - flask-wtf
  - dash
  - pandas
  - numpy
  - plotly
  - openai
  - groq
  - xai-sdk
  - mcp
  - uvicorn
  - python-dotenv
